### ISSUE TITLE
glusto tests are not getting collected for centos-ci

### ISSUE THREAD

**Issue by balakreddy** [gluster/centosci#105]
On triggering "/run tests", Centos-ci is failing with no inventory is available. The issues are seen from today morning. Till yesterday the runs are getting successful.
Last successful build was: https://ci.centos.org/job/gluster_glusto-patch-check/2224/
after that seeing continuous failures.

Ref failure: https://ci.centos.org/job/gluster_glusto-patch-check/2228/console

log snippet:
```
12:04:27  > git rev-list --no-walk 830967b066c8f37cccdde3cdf45dec815641e542 # timeout=10
12:04:27 [gluster_glusto-patch-check] $ /bin/sh -xe /tmp/jenkins4256445127212979055.sh
12:04:27 + set +x
12:04:38 The requested operation failed as no inventory is available.
12:04:38 Build step 'Execute shell' marked build as failure
12:04:38 Archiving artifacts
12:04:38 Archiving artifacts
12:04:38 Performing Post build task...
12:04:38 Match found for :Building remotely : True
12:04:38 Logical operation result is TRUE
12:04:38 Running script  : # cico-node-done-from-ansible.sh
12:04:38 # A script that releases nodes from a SSID file written by
12:04:38 SSID_FILE=${SSID_FILE:-$WORKSPACE/cico-ssid}
12:04:38 
12:04:38 for ssid in $(cat ${SSID_FILE})
12:04:38 do
12:04:38     cico -q node done $ssid
12:04:38 done
12:04:38 
12:04:38 [gluster_glusto-patch-check] $ /bin/sh -xe /tmp/jenkins5753623299420350755.sh
12:04:38 + SSID_FILE=/home/gluster/workspace/gluster_glusto-patch-check/cico-ssid
12:04:38 ++ cat /home/gluster/workspace/gluster_glusto-patch-check/cico-ssid
12:04:38 cat: /home/gluster/workspace/gluster_glusto-patch-check/cico-ssid: No such file or directory
12:04:38 POST BUILD TASK : SUCCESS
12:04:38 END OF POST BUILD TASK : 0
12:04:39 Finished: FAILURE
```

**Comment by balakreddy** [comment]
@deepshikhaaa I am seeing this issue again. Can you take a look at it.

20:18:51 Checking out Revision aabec550779e17925406d00588b4bd8e839a160e (refs/remotes/origin/master)
20:18:51  > git config core.sparsecheckout # timeout=10
20:18:51  > git checkout -f aabec550779e17925406d00588b4bd8e839a160e
20:18:51 Commit message: "Delete the jobs which are failing for more than an year and are inactive"
20:18:51  > git rev-list --no-walk aabec550779e17925406d00588b4bd8e839a160e # timeout=10
20:18:51 [gluster_glusto-patch-check] $ /bin/sh -xe /tmp/jenkins6299907108972341694.sh
20:18:51 + set +x
20:19:02 The requested operation failed as no inventory is available.
20:19:02 Build step 'Execute shell' marked build as failure
20:19:02 Archiving artifacts
20:19:02 Archiving artifacts
20:19:02 Performing Post build task...
20:19:02 Match found for :Building remotely : True
20:19:02 Logical operation result is TRUE
20:19:02 Running script  : # cico-node-done-from-ansible.sh
20:19:02 # A script that releases nodes from a SSID file written by
20:19:02 SSID_FILE=${SSID_FILE:-$WORKSPACE/cico-ssid}
20:19:02 
20:19:02 for ssid in $(cat ${SSID_FILE})
20:19:02 do
20:19:02     cico -q node done $ssid
20:19:02 done
20:19:02 
20:19:02 [gluster_glusto-patch-check] $ /bin/sh -xe /tmp/jenkins1100894817122121456.sh
20:19:02 + SSID_FILE=/home/gluster/workspace/gluster_glusto-patch-check/cico-ssid
20:19:02 ++ cat /home/gluster/workspace/gluster_glusto-patch-check/cico-ssid
20:19:02 cat: /home/gluster/workspace/gluster_glusto-patch-check/cico-ssid: No such file or directory
20:19:02 POST BUILD TASK : SUCCESS
20:19:02 END OF POST BUILD TASK : 0
20:19:02 Finished: FAILURE

Reference for failure: https://ci.centos.org/job/gluster_glusto-patch-check/2316/console

**Comment by deepshikhaaa** [comment]
I think it is a network issue or some outage with centos ci infra, cico machines that might not be coming up and are not added in the inventory. You might need to bring it to the centos ci team notice.

**Comment by kshithijiyer** [comment]
@balakreddy Are you still hitting this issue?

**Comment by balakreddy** [comment]
Not hitting this issue will close it.
