### ISSUE TITLE
centos-ci failing for glusto-tests

### ISSUE THREAD

**Issue by UpasanaBansal** [gluster/centosci#109]
Centos-CI is failing for glusto-tests with the below error

16:48:35 [gluster_glusto-patch-check] $ /bin/sh -xe /tmp/jenkins4150740014090108549.sh
16:48:35 + SSID_FILE=/home/gluster/workspace/gluster_glusto-patch-check/cico-ssid
16:48:35 ++ cat /home/gluster/workspace/gluster_glusto-patch-check/cico-ssid
16:48:35 cat: /home/gluster/workspace/gluster_glusto-patch-check/cico-ssid: No such file or directory
 POST BUILD TASK : SUCCESS
16:48:35 END OF POST BUILD TASK : 0
16:48:35 Finished: FAILURE

**Comment by kshithijiyer** [comment]
@UpasanaBansal Are you still seeing this issue?

**Comment by kshithijiyer** [comment]
As we are no longer hitting this issue hence closing it.
