### ISSUE TITLE
Update glusterfs at Glusto patch check job

### ISSUE THREAD

**Issue by sunilheggodu** [gluster/centosci#124]
Glusto Patch Check job : https://ci.centos.org/job/gluster_glusto-patch-check/ is currently using glusterfs builds from master branch. Please update the job to use latest devel build.

**Comment by kshithijiyer** [comment]
As  a fix https://github.com/gluster/centosci/commit/f431645c31bb1eb5eb5446bd92895ffa339d03be has been sent and merged for this issue, 

@deepshikhaaa can you please close this issue?
