### ISSUE TITLE
CI jobs failing after renaming branch master to main

### ISSUE THREAD

**Issue by obnoxxx** [gluster/centosci#148]
Despite having changed the branch from `origin/master` to `origin/main` for the nightly-samba-builds job in #143 (and others as well), the jobs still fail like this:

```
Cloning the remote Git repository
Cloning repository https://github.com/gluster/centosci.git
 > git init /home/gluster/workspace/gluster_nightly-samba-rpm-builds # timeout=10
Fetching upstream changes from https://github.com/gluster/centosci.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
 > git fetch --tags --progress https://github.com/gluster/centosci.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/gluster/centosci.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse origin/master^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
```

Seems like there is some problem with the system still having the master branch located somewhere.

See e.g. https://ci.centos.org/view/Gluster/job/gluster_nightly-samba-rpm-builds/391/console (latest nightly) or https://ci.centos.org/view/Gluster/job/gluster_nightly-samba-rpm-builds/390/console triggered from https://github.com/gluster/samba-integration/pull/137

**Comment by obnoxxx** [comment]
@nixpanic - any clues?

Some googling indicated avoiding the second fetch may introduce the problems.
Some leads indicate an `allowSecondFetch` option to the git plugin, but I don't know how or where to set it.

**Comment by nixpanic** [comment]
![jenkins-git-2nd-fetch](https://user-images.githubusercontent.com/400257/108678148-febe8480-74ea-11eb-9415-6af39819e69b.png)

This options is under the `https://<jenkins-host>/configure` page. Because Gluster still uses the shared Jenkins deployment, changing this option requires a ticket at https://pagure.io/centos-infra/issues

**Comment by nixpanic** [comment]
Requested the option at https://pagure.io/centos-infra/issue/230

**Comment by obnoxxx** [comment]
Thanks @nixpanic - let's see if that helps...

**Comment by obnoxxx** [comment]
This seems to be fixed with #149

**Comment by anoopcs9** [comment]
> Requested the option at https://pagure.io/centos-infra/issue/230

So did we make a change with Jenkins configuration for git plugin?

**Comment by anoopcs9** [comment]
Closing the issue as we are successfully running the integration job in Jenkins for a while now.
