### ISSUE TITLE
Create el9 nightly builds for GlusterFS

### ISSUE THREAD

**Issue by anoopcs9** [gluster/centosci#186]
In addition to el8, it would be great to have el9 builds for GlusterFS. From a consumer perspective we [build](https://github.com/gluster/samba-integration/tree/samba-build) and test Samba with GlusterFS integration using nightly builds [repo](http://artifacts.ci.centos.org/gluster/nightly/master.repo) for devel branch. These Samba builds are used in [samba-container](https://github.com/samba-in-kubernetes/samba-container) project eventually getting consumed by [samba-operator](https://github.com/samba-in-kubernetes/samba-operator/). Moving forward our plan is to create el9 builds for which corresponding GlusterFS builds will be a prerequisite.

**Comment by rakshithakamath94** [comment]
Changes have been merged successfully!
