### ISSUE TITLE
Failed to install gluster-block from nightly build

### ISSUE THREAD

**Issue by Madhu-1** [gluster/centosci#52]
used this repo file to install gluster-block from the nightly build
http://artifacts.ci.centos.org/gluster/gluster-block-nightly/gluster-block.repo

but facing below issue 
`failure: repodata/repomd.xml from gluster-block-nightly-master: [Errno 256] No more mirrors to try.
http://artifacts.ci.centos.org/gluster/gluster-block-nightly/master/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found`

**Comment by Madhu-1** [comment]
@nixpanic @nigelbabu ^^

**Comment by nixpanic** [comment]
The script has been updated and a [new run of the job has been triggered](https://ci.centos.org/view/Gluster/job/gluster_block_basic/44/console). Please watch the output of the job and verify that a `repodata` directory exists afterwards under http://artifacts.ci.centos.org/gluster/gluster-block-nightly/master/7/x86_64/
